#端口设置
server:
  port: 7003

eureka:
  # server:
   # enable-self-preservation: false    禁用保护机制
  instance:
    hostname: eureka7003.com #服务端的实例名称     单机版：localhost
  client:
    register-with-eureka: false  #表示不向注册中心注册自己
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
      #单机defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/   #eureka service地址查询和交互注册服务都需要依赖地址       类似于对外约定的地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   #eureka service地址查询和交互注册服务都需要依赖地址       类似于对外约定的地址

